### ISSUE TITLE
SFH 409 nicht mehr erhältlich?

### ISSUE THREAD

**Issue by andi-blafasl** [skaringa/emeir#1]
Hallo Herr Kompf,

ich bin schon länger auf der Suche nach einem Sensor für Ferrari-Zähler der einfach zu bauen ist und zuverlässig funktioniert. Ihren Ansatz mit einem Arduino finde ich sehr interessant und werde ihn nachbauen. Vielen Dank für die gute Doku und die Quelltexte!

Leider ist die IR Diode [SFH 409](http://cdn-reichelt.de/documents/datenblatt/A500/SFH4346.pdf) wohl nicht mehr im Handel erhältlich. Nach einer Recherche im Netz habe ich mich für die [SFH 4346](http://cdn-reichelt.de/documents/datenblatt/A500/SFH4346.pdf) entschieden. Laut Datenblatt hat sie, so weit ich das verstanden habe, die gleichen elektrischen Daten wie die SFH 409, bietet aber eine höhere Lichtstärke und schneller Schaltzeiten. Ich hoffe das es dadurch keine Probleme bei der Auswertung mit dem SFH 309 FA gibt. Wie sehen Sie die SFH 4346 als alternative? Oder haben Sie einen besseren Vorschlag?

Ein kleiner Testaufbau auf einem Steckbrett hat heute schon mal funktioniert. Ein Finger der an der Lichtschranke vorbei geführt wird, erzeugt Daten im RAW Mode zwischen ~120 und ~800. Mit entsprechenden Trigger-Werten bekomme ich dann auch 0er und 1er ;-)

Bin gespannt ob der Sensor auch am Zähler funktioniert. Ich werde berichten, sobald ich es eingebaut habe.

Grüße,
Andreas

**Comment by skaringa** [comment]
Laut Datenblatt müsste die SFH 4346 auch funktionieren, danke für den Tipp!

**Comment by andi-blafasl** [comment]
Ich habe den Sensor jetzt fertig aufgebaut und ein erster test am Strom- und Wasserzähler wahr vielversprechend! Der rote Strich und der Halbmond werden erkannt. Jetzt muss ich das ganze nur noch final montieren, dann sollte der Erfassung nichts mehr im Wege stehen.

Für alle Nachbauer ist der SFH 4346 eine gut verwendbare alternative zum SFH 409. Man muss nur gut aufpassen das man die IR Diode nicht mit dem Fototransistor SFH 309 FA vertauscht! Beide sehen nämlich absolut identisch aus...
