### ISSUE TITLE
SFH 4346 auch nicht mehr erhältlich

### ISSUE THREAD

**Issue by blissi** [skaringa/emeir#2]
Hi,
der SFH 4346 ist leider auch nicht mehr im Handel erhältlich :-(.
Gibt es eine Alternative bzw. auf was muss ich denn schauen? Kenne mich mit IR leider gar nicht aus.

Danke schonmal

**Comment by skaringa** [comment]
One could try the [TCRT5000](https://www.ebay.de/itm/255283221953). It contains both IR transmitter and receiver and works well with arduino.

**Comment by pschichtel** [comment]
> One could try the [TCRT5000](https://www.ebay.de/itm/255283221953). It contains both IR transmitter and receiver and works well with arduino.

Can confirm.
